In [11]:
import requests
import pandas as pd
import json
from config import API_Key
import csv
import numpy as np

In [2]:
df = pd.read_csv('data/Satellite-Exploration-CSV.csv')

In [3]:
df

,Name,NORAD ID,Source,Launch Site
0,HYSIS,43719,India,SRIHARIKOTA (SRI)
1,GAOFEN-5,43461,People's Republic of China,"Taiyaun Space Center, China (TSC)"
2,NUSAT 5,43204,Argentina,"Jiuquan Satellite Launch Center, China (JSC)"
3,NUSAT 4,43195,Argentina,"Jiuquan Satellite Launch Center, China (JSC)"
4,VRSS-2,42954,Venezuela,"Jiuquan Satellite Launch Center, China (JSC)"
...,...,...,...,...
144,LANDSAT 4,13367,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
145,SEASAT 1,10967,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
146,LANDSAT 3,10702,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
147,LANDSAT 2,7615,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
148,LANDSAT 1,6126,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)

In [4]:
df.set_index(["Name"])

,NORAD ID,Source,Launch Site
Name,,,
HYSIS,43719,India,SRIHARIKOTA (SRI)
GAOFEN-5,43461,People's Republic of China,"Taiyaun Space Center, China (TSC)"
NUSAT 5,43204,Argentina,"Jiuquan Satellite Launch Center, China (JSC)"
NUSAT 4,43195,Argentina,"Jiuquan Satellite Launch Center, China (JSC)"
VRSS-2,42954,Venezuela,"Jiuquan Satellite Launch Center, China (JSC)"
...,...,...,...
LANDSAT 4,13367,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
SEASAT 1,10967,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
LANDSAT 3,10702,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
LANDSAT 2,7615,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)
LANDSAT 1,6126,United States,AIR FORCE WESTERN TEST RANGE (AFWTR)

In [18]:
array = np.array(df)
id= array[:,1]

In [20]:
for x in id:
    base_url = f"https://api.n2yo.com/rest/v1/satellite/positions/{x}/40.0583/74.4057/0/1/&apiKey=87BK3U-D8QTDU-BVBZ4W-4LL1"
    response = requests.get(base_url)
    data = response.json()
    print(json.dumps(data, indent =4, sort_keys=True))

{
    "info": {
        "satid": 43719,
        "satname": "HYSIS",
        "transactionscount": 150
    },
    "positions": [
        {
            "azimuth": 117.07,
            "dec": -43.69666729,
            "eclipsed": false,
            "elevation": -42.54,
            "ra": 255.35924809,
            "sataltitude": 642.13,
            "satlatitude": -20.95074784,
            "satlongitude": 146.4760698,
            "timestamp": 1606435265
        }
    ]
}
{
    "info": {
        "satid": 43461,
        "satname": "GAOFEN-5",
        "transactionscount": 151
    },
    "positions": [
        {
            "azimuth": 197.79,
            "dec": -64.82365608,
            "eclipsed": false,
            "elevation": -63.02,
            "ra": 339.7047389,
            "sataltitude": 727.46,
            "satlatitude": -76.3561914,
            "satlongitude": -16.04568597,
            "timestamp": 1606435266
        }
    ]
}
{
    "info": {
        "satid": 43204,
        "satname": "NUSAT 5",
        "transactionscount": 152
    },
    "positions": [
        {
            "azimuth": 343.74,
            "dec": 28.6493441,
            "eclipsed": true,
            "elevation": -19.29,
            "ra": 338.42702655,
            "sataltitude": 513.59,
            "satlatitude": 77.64398405,
            "satlongitude": -3.01193512,
            "timestamp": 1606435266
        }
    ]
}
{
    "info": {
        "satid": 43195,
        "satname": "NUSAT 4",
        "transactionscount": 153
    },
    "positions": [
        {
            "azimuth": 156.34,
            "dec": -60.13310136,
            "eclipsed": false,
            "elevation": -66.91,
            "ra": 302.19465854,
            "sataltitude": 506.87,
            "satlatitude": -72.06470432,
            "satlongitude": -170.54236457,
            "timestamp": 1606435268
        }
    ]
}
{
    "info": {
        "satid": 42954,
        "satname": "VRSS-2",
        "transactionscount": 154
    },
    "positions": [
        {
            "azimuth": 336.14,
            "dec": 19.53075081,
            "eclipsed": true,
            "elevation": -26.67,
            "ra": 343.43029673,
            "sataltitude": 660.95,
            "satlatitude": 66.63566002,
            "satlongitude": -40.92219167,
            "timestamp": 1606435268
        }
    ]
}
{
    "info": {
        "satid": 42901,
        "satname": "VENUS",
        "transactionscount": 155
    },
    "positions": [
        {
            "azimuth": 327.79,
            "dec": 14.99427124,
            "eclipsed": true,
            "elevation": -28.55,
            "ra": 349.86340751,
            "sataltitude": 701.19,
            "satlatitude": 58.48302158,
            "satlongitude": -36.83461385,
            "timestamp": 1606435269
        }
    ]
}
{
    "info": {
        "satid": 42063,
        "satname": "SENTINEL 2B",
        "transactionscount": 156
    },
    "positions": [
        {
            "azimuth": 140.48,
            "dec": -60.32630117,
            "eclipsed": false,
            "elevation": -53.11,
            "ra": 269.98093014,
            "sataltitude": 809.72,
            "satlatitude": -51.53727657,
            "satlongitude": 146.36009066,
            "timestamp": 1606435270
        }
    ]
}
{
    "info": {
        "satid": 41898,
        "satname": "TANSAT",
        "transactionscount": 157
    },
    "positions": [
        {
            "azimuth": 11.81,
            "dec": 31.97156153,
            "eclipsed": false,
            "elevation": -16.8,
            "ra": 307.44225193,
            "sataltitude": 701.04,
            "satlatitude": 80.75034147,
            "satlongitude": 143.09110508,
            "timestamp": 1606435271
        }
    ]
}
{
    "info": {
        "satid": 41877,
        "satname": "RESOURCESAT 2A",
        "transactionscount": 158
    },
    "positions": [
        {
            "azimuth": 127.3,
            "dec": -52.01893501,
            "eclipsed": false,
            "elevation": -48.1,
            "ra": 260.83942396,
            "sataltitude": 833.85,
            "satlatitude": -36.12391779,
            "satlongitude": 148.17625331,
            "timestamp": 1606435271
        }
    ]
}
{
    "info": {
        "satid": 41848,
        "satname": "WORLDVIEW-4",
        "transactionscount": 159
    },
    "positions": [
        {
            "azimuth": 350.8,
            "dec": 26.09608523,
            "eclipsed": true,
            "elevation": -23.18,
            "ra": 330.33480353,
            "sataltitude": 463.42,
            "satlatitude": 81.63656487,
            "satlongitude": -42.81336489,
            "timestamp": 1606435272
        }
    ]
}
{
    "info": {
        "satid": 41599,
        "satname": "CARTOSAT 2C",
        "transactionscount": 160
    },
    "positions": [
        {
            "azimuth": 58.71,
            "dec": 6.97097631,
            "eclipsed": false,
            "elevation": -22.54,
            "ra": 268.21771567,
            "sataltitude": 520.25,
            "satlatitude": 44.47519054,
            "satlongitude": 149.71471619,
            "timestamp": 1606435273
        }
    ]
}
{
    "info": {
        "satid": 41558,
        "satname": "NUSAT 2 (BATATA)",
        "transactionscount": 161
    },
    "positions": [
        {
            "azimuth": 48.29,
            "dec": 1.77976728,
            "eclipsed": false,
            "elevation": -36.2,
            "ra": 283.78204477,
            "sataltitude": 478.88,
            "satlatitude": 39.4919069,
            "satlongitude": -176.44661714,
            "timestamp": 1606435274
        }
    ]
}
{
    "info": {
        "satid": 41558,
        "satname": "NUSAT 2 (BATATA)",
        "transactionscount": 162
    },
    "positions": [
        {
            "azimuth": 48.29,
            "dec": 1.77976728,
            "eclipsed": false,
            "elevation": -36.2,
            "ra": 283.78204477,
            "sataltitude": 478.88,
            "satlatitude": 39.4919069,
            "satlongitude": -176.44661714,
            "timestamp": 1606435274
        }
    ]
}
{
    "info": {
        "satid": 41557,
        "satname": "NUSAT 1 (FRESCO)",
        "transactionscount": 163
    },
    "positions": [
        {
            "azimuth": 118.1,
            "dec": -47.3515309,
            "eclipsed": false,
            "elevation": -56.69,
            "ra": 275.01435178,
            "sataltitude": 486.53,
            "satlatitude": -37.58786174,
            "satlongitude": 168.79163576,
            "timestamp": 1606435275
        }
    ]
}
{
    "info": {
        "satid": 41557,
        "satname": "NUSAT 1 (FRESCO)",
        "transactionscount": 164
    },
    "positions": [
        {
            "azimuth": 118.17,
            "dec": -47.38937732,
            "eclipsed": false,
            "elevation": -56.71,
            "ra": 275.03103892,
            "sataltitude": 486.55,
            "satlatitude": -37.65083401,
            "satlongitude": 168.77443995,
            "timestamp": 1606435276
        }
    ]
}
{
    "info": {
        "satid": 41556,
        "satname": "ZIYUAN 3-2",
        "transactionscount": 165
    },
    "positions": [
        {
            "azimuth": 156.17,
            "dec": -66.78193061,
            "eclipsed": false,
            "elevation": -57.51,
            "ra": 287.11724139,
            "sataltitude": 527.27,
            "satlatitude": -66.89379601,
            "satlongitude": 139.21861282,
            "timestamp": 1606435277
        }
    ]
}
{
    "info": {
        "satid": 41456,
        "satname": "SENTINEL 1B",
        "transactionscount": 166
    },
    "positions": [
        {
            "azimuth": 358.5,
            "dec": 11.65366106,
            "eclipsed": false,
            "elevation": -38.15,
            "ra": 322.06693781,
            "sataltitude": 704.45,
            "satlatitude": 56.90070358,
            "satlongitude": -102.87275333,
            "timestamp": 1606435278
        }
    ]
}
{
    "info": {
        "satid": 41386,
        "satname": "RESURS P3",
        "transactionscount": 167
    },
    "positions": [
        {
            "azimuth": 10.37,
            "dec": 23.61274038,
            "eclipsed": false,
            "elevation": -25.56,
            "ra": 310.73324477,
            "sataltitude": 481.12,
            "satlatitude": 78.03673477,
            "satlongitude": -153.24639831,
            "timestamp": 1606435279
        }
    ]
}

{
    "info": {
        "satid": 41335,
        "satname": "SENTINEL-3A",
        "transactionscount": 168
    },
    "positions": [
        {
            "azimuth": 326.07,
            "dec": 12.0846503,
            "eclipsed": true,
            "elevation": -31.06,
            "ra": 350.17440155,
            "sataltitude": 810.67,
            "satlatitude": 53.72599578,
            "satlongitude": -42.16047531,
            "timestamp": 1606435280
        }
    ]
}
{
    "info": {
        "satid": 40968,
        "satname": "BISONSAT",
        "transactionscount": 169
    },
    "positions": [
        {
            "azimuth": 317.39,
            "dec": -27.70345405,
            "eclipsed": false,
            "elevation": -73.96,
            "ra": 332.98507685,
            "sataltitude": 535.27,
            "satlatitude": -15.59652734,
            "satlongitude": -84.50005887,
            "timestamp": 1606435281
        }
    ]
}
{
    "info": {
        "satid": 40931,
        "satname": "LAPAN A2 (IO-86)",
        "transactionscount": 170
    },
    "positions": [
        {
            "azimuth": 4.51,
            "dec": -16.25437426,
            "eclipsed": false,
            "elevation": -66.05,
            "ra": 318.88841642,
            "sataltitude": 627.22,
            "satlatitude": 5.31909042,
            "satlongitude": -108.83363058,
            "timestamp": 1606435282
        }
    ]
}
{
    "info": {
        "satid": 40701,
        "satname": "GAOFEN 8",
        "transactionscount": 171
    },
    "positions": [
        {
            "azimuth": 208,
            "dec": -69.06321543,
            "eclipsed": false,
            "elevation": -43.31,
            "ra": 32.8616175,
            "sataltitude": 506.11,
            "satlatitude": -43.41141263,
            "satlongitude": 34.41422547,
            "timestamp": 1606435284
        }
    ]
}
{
    "info": {
        "satid": 40697,
        "satname": "SENTINEL 2A",
        "transactionscount": 172
    },
    "positions": [
        {
            "azimuth": 321.31,
            "dec": 11.50508546,
            "eclipsed": true,
            "elevation": -29.57,
            "ra": 354.61777183,
            "sataltitude": 796.74,
            "satlatitude": 52.12277108,
            "satlongitude": -33.93280734,
            "timestamp": 1606435284
        }
    ]
}
{
    "info": {
        "satid": 40536,
        "satname": "KOMPSAT 3A",
        "transactionscount": 173
    },
    "positions": [
        {
            "azimuth": 319.28,
            "dec": 29.79201016,
            "eclipsed": true,
            "elevation": -6.98,
            "ra": 9.02793422,
            "sataltitude": 539.6,
            "satlatitude": 58.20416168,
            "satlongitude": 35.22250832,
            "timestamp": 1606435285
        }
    ]
}
{
    "info": {
        "satid": 40360,
        "satname": "RESURS P2",
        "transactionscount": 174
    },
    "positions": [
        {
            "azimuth": 137.62,
            "dec": -57.53476918,
            "eclipsed": false,
            "elevation": -58.62,
            "ra": 279.7986902,
            "sataltitude": 486.45,
            "satlatitude": -54.28613271,
            "satlongitude": 160.76539891,
            "timestamp": 1606435286
        }
    ]
}
{
    "info": {
        "satid": 40336,
        "satname": "CBERS-4",
        "transactionscount": 175
    },
    "positions": [
        {
            "azimuth": 216.86,
            "dec": -60.42047389,
            "eclipsed": false,
            "elevation": -58.59,
            "ra": 359.91256237,
            "sataltitude": 796.93,
            "satlatitude": -59.08295666,
            "satlongitude": -9.99572408,
            "timestamp": 1606435287
        }
    ]
}
{
    "info": {
        "satid": 40118,
        "satname": "GAOFEN 2",
        "transactionscount": 176
    },
    "positions": [
        {
            "azimuth": 353.92,
            "dec": 25.21432383,
            "eclipsed": false,
            "elevation": -24.37,
            "ra": 327.1058685,
            "sataltitude": 638.86,
            "satlatitude": 80.20402946,
            "satlongitude": -73.6264672,
            "timestamp": 1606435288
        }
    ]
}
{
    "info": {
        "satid": 40072,
        "satname": "SKYSAT 2",
        "transactionscount": 177
    },
    "positions": [
        {
            "azimuth": 183.8,
            "dec": -50.88941429,
            "eclipsed": false,
            "elevation": -79.2,
            "ra": 321.93626283,
            "sataltitude": 649.55,
            "satlatitude": -60.9065826,
            "satlongitude": -102.86128809,
            "timestamp": 1606435289
        }
    ]
}
{
    "info": {
        "satid": 40053,
        "satname": "SPOT 7",
        "transactionscount": 178
    },
    "positions": [
        {
            "azimuth": 139.52,
            "dec": -60.07082793,
            "eclipsed": false,
            "elevation": -50.32,
            "ra": 264.35483543,
            "sataltitude": 716.6,
            "satlatitude": -47.15949457,
            "satlongitude": 140.80772277,
            "timestamp": 1606435290
        }
    ]
}
{
    "info": {
        "satid": 39766,
        "satname": "ALOS 2",
        "transactionscount": 179
    },
    "positions": [
        {
            "azimuth": 89.48,
            "dec": -29.98268473,
            "eclipsed": false,
            "elevation": -51.61,
            "ra": 275.00699635,
            "sataltitude": 636.21,
            "satlatitude": -10.83693846,
            "satlongitude": 178.00508539,
            "timestamp": 1606435291
        }
    ]
}
{
    "info": {
        "satid": 39731,
        "satname": "KAZEOSAT 1",
        "transactionscount": 180
    },
    "positions": [
        {
            "azimuth": 153.32,
            "dec": -66.73426072,
            "eclipsed": false,
            "elevation": -55.23,
            "ra": 280.14091179,
            "sataltitude": 776.49,
            "satlatitude": -62.96309843,
            "satlongitude": 137.52871634,
            "timestamp": 1606435292
        }
    ]
}
{
    "info": {
        "satid": 39455,
        "satname": "SHIYAN-5 (SY-5)",
        "transactionscount": 181
    },
    "positions": [
        {
            "azimuth": 72.48,
            "dec": -21.28992175,
            "eclipsed": false,
            "elevation": -51.69,
            "ra": 281.49973669,
            "sataltitude": 739.91,
            "satlatitude": 1.01807719,
            "satlongitude": -170.77654591,
            "timestamp": 1606435293
        }
    ]
}
{
    "info": {
        "satid": 39422,
        "satname": "STSAT 3",
        "transactionscount": 182
    },
    "positions": [
        {
            "azimuth": 69.61,
            "dec": 11.17004121,
            "eclipsed": false,
            "elevation": -6.55,
            "ra": 249.41993785,
            "sataltitude": 612.82,
            "satlatitude": 43.48716323,
            "satlongitude": 116.88509964,
            "timestamp": 1606435293
        }
    ]
}
{
    "info": {
        "satid": 39419,
        "satname": "DUBAISAT 2",
        "transactionscount": 183
    },
    "positions": [
        {
            "azimuth": 349,
            "dec": 20.3329093,
            "eclipsed": true,
            "elevation": -28.72,
            "ra": 331.25387212,
            "sataltitude": 590.09,
            "satlatitude": 72.11782866,
            "satlongitude": -71.30854972,
            "timestamp": 1606435294
        }
    ]
}
{
    "info": {
        "satid": 39418,
        "satname": "SKYSAT 1",
        "transactionscount": 184
    },
    "positions": [
        {
            "azimuth": 158.45,
            "dec": -67.14848838,
            "eclipsed": false,
            "elevation": -58.36,
            "ra": 290.85110293,
            "sataltitude": 604.38,
            "satlatitude": -69.65166101,
            "satlongitude": 140.09138195,
            "timestamp": 1606435296
        }
    ]
}
{
    "info": {
        "satid": 39186,
        "satname": "RESURS P1",
        "transactionscount": 185
    },
    "positions": [
        {
            "azimuth": 57.1,
            "dec": 6.5329317,
            "eclipsed": false,
            "elevation": -24.38,
            "ra": 270.64810823,
            "sataltitude": 473.34,
            "satlatitude": 44.63713289,
            "satlongitude": 153.67555372,
            "timestamp": 1606435297
        }
    ]
}

{
    "info": {
        "satid": 39160,
        "satname": "VNREDSAT 1",
        "transactionscount": 186
    },
    "positions": [
        {
            "azimuth": 124.76,
            "dec": -50.68269349,
            "eclipsed": false,
            "elevation": -50.49,
            "ra": 265.09903084,
            "sataltitude": 698.3,
            "satlatitude": -36.56199207,
            "satlongitude": 153.56047779,
            "timestamp": 1606435298
        }
    ]
}
{
    "info": {
        "satid": 39159,
        "satname": "PROBA V",
        "transactionscount": 187
    },
    "positions": [
        {
            "azimuth": 274.32,
            "dec": -31.06765236,
            "eclipsed": true,
            "elevation": -57.79,
            "ra": 359.20211848,
            "sataltitude": 819.33,
            "satlatitude": -15.7815894,
            "satlongitude": -41.38603243,
            "timestamp": 1606435298
        }
    ]
}
{
    "info": {
        "satid": 39150,
        "satname": "GAOFEN 1",
        "transactionscount": 188
    },
    "positions": [
        {
            "azimuth": 119.26,
            "dec": -46.73705994,
            "eclipsed": false,
            "elevation": -48.1,
            "ra": 262.47308586,
            "sataltitude": 655.05,
            "satlatitude": -29.46024912,
            "satlongitude": 153.33585528,
            "timestamp": 1606435300
        }
    ]
}
{
    "info": {
        "satid": 39086,
        "satname": "SARAL",
        "transactionscount": 189
    },
    "positions": [
        {
            "azimuth": 344.82,
            "dec": 9.07434659,
            "eclipsed": false,
            "elevation": -39.6,
            "ra": 332.72703009,
            "sataltitude": 791.89,
            "satlatitude": 51.14762884,
            "satlongitude": -80.99955733,
            "timestamp": 1606435300
        }
    ]
}
{
    "info": {
        "satid": 39084,
        "satname": "LANDSAT 8",
        "transactionscount": 190
    },
    "positions": [
        {
            "azimuth": 242.59,
            "dec": -47.12147154,
            "eclipsed": true,
            "elevation": -56.39,
            "ra": 7.00414606,
            "sataltitude": 717.38,
            "satlatitude": -37.3307334,
            "satlongitude": -20.96496116,
            "timestamp": 1606435301
        }
    ]
}
{
    "info": {
        "satid": 39030,
        "satname": "GOKTURK 2",
        "transactionscount": 191
    },
    "positions": [
        {
            "azimuth": 247.58,
            "dec": -44.99636342,
            "eclipsed": false,
            "elevation": -63.07,
            "ra": 357.18939053,
            "sataltitude": 668.71,
            "satlatitude": -39.42895836,
            "satlongitude": -37.33791279,
            "timestamp": 1606435302
        }
    ]
}
{
    "info": {
        "satid": 38782,
        "satname": "VRSS-1",
        "transactionscount": 192
    },
    "positions": [
        {
            "azimuth": 345.71,
            "dec": 20.17867359,
            "eclipsed": true,
            "elevation": -28.35,
            "ra": 334.3990671,
            "sataltitude": 650.22,
            "satlatitude": 70.54188209,
            "satlongitude": -63.36466464,
            "timestamp": 1606435303
        }
    ]
}
{
    "info": {
        "satid": 38755,
        "satname": "SPOT 6",
        "transactionscount": 193
    },
    "positions": [
        {
            "azimuth": 324.43,
            "dec": 10.5201289,
            "eclipsed": true,
            "elevation": -32.12,
            "ra": 351.06474505,
            "sataltitude": 705.63,
            "satlatitude": 52.02921785,
            "satlongitude": -41.36297845,
            "timestamp": 1606435303
        }
    ]
}
{
    "info": {
        "satid": 38708,
        "satname": "BKA 2",
        "transactionscount": 194
    },
    "positions": [
        {
            "azimuth": 20.54,
            "dec": 29.33692944,
            "eclipsed": false,
            "elevation": -17.41,
            "ra": 298.30640901,
            "sataltitude": 517.41,
            "satlatitude": 74.22745436,
            "satlongitude": 140.98400414,
            "timestamp": 1606435304
        }
    ]
}
{
    "info": {
        "satid": 38707,
        "satname": "KANOPUS-V 1",
        "transactionscount": 195
    },
    "positions": [
        {
            "azimuth": 243.14,
            "dec": -44.57084598,
            "eclipsed": true,
            "elevation": -45.35,
            "ra": 22.53103949,
            "sataltitude": 517.23,
            "satlatitude": -23.71380657,
            "satlongitude": -1.21386995,
            "timestamp": 1606435305
        }
    ]
}
{
    "info": {
        "satid": 38248,
        "satname": "RISAT 1",
        "transactionscount": 196
    },
    "positions": [
        {
            "azimuth": 9.09,
            "dec": 27.71712469,
            "eclipsed": false,
            "elevation": -21.54,
            "ra": 311.46245391,
            "sataltitude": 545.71,
            "satlatitude": 82.47531537,
            "satlongitude": -178.49252002,
            "timestamp": 1606435305
        }
    ]
}
{
    "info": {
        "satid": 38038,
        "satname": "ZY 1",
        "transactionscount": 197
    },
    "positions": [
        {
            "azimuth": 25.2,
            "dec": 25.81191019,
            "eclipsed": false,
            "elevation": -19.64,
            "ra": 294.62383323,
            "sataltitude": 781.38,
            "satlatitude": 70.27244337,
            "satlongitude": 163.93573762,
            "timestamp": 1606435307
        }
    ]
}
{
    "info": {
        "satid": 37794,
        "satname": "SICH 2",
        "transactionscount": 198
    },
    "positions": [
        {
            "azimuth": 155.27,
            "dec": -69.67174483,
            "eclipsed": false,
            "elevation": -50.92,
            "ra": 271.11452378,
            "sataltitude": 715.78,
            "satlatitude": -58.11881227,
            "satlongitude": 123.439834,
            "timestamp": 1606435307
        }
    ]
}
{
    "info": {
        "satid": 37781,
        "satname": "HAIYANG 2A",
        "transactionscount": 199
    },
    "positions": [
        {
            "azimuth": 191.57,
            "dec": -67.27772676,
            "eclipsed": false,
            "elevation": -61.81,
            "ra": 334.96344667,
            "sataltitude": 996.66,
            "satlatitude": -80.71471102,
            "satlongitude": -3.38234617,
            "timestamp": 1606435308
        }
    ]
}
{
    "info": {
        "satid": 37387,
        "satname": "RESOURCESAT 2",
        "transactionscount": 200
    },
    "positions": [
        {
            "azimuth": 260.61,
            "dec": -34.79225398,
            "eclipsed": true,
            "elevation": -49.14,
            "ra": 12.65558458,
            "sataltitude": 825.59,
            "satlatitude": -16.14816498,
            "satlongitude": -20.27051434,
            "timestamp": 1606435309
        }
    ]
}
{
    "info": {
        "satid": 36985,
        "satname": "TIANHUI 1",
        "transactionscount": 201
    },
    "positions": [
        {
            "azimuth": 7.29,
            "dec": 49.67483327,
            "eclipsed": false,
            "elevation": 0.31,
            "ra": 309.62653697,
            "sataltitude": 491.87,
            "satlatitude": 61.29019754,
            "satlongitude": 79.94248984,
            "timestamp": 1606435310
        }
    ]
}
{
    "info": {
        "satid": 36795,
        "satname": "CARTOSAT 2B",
        "transactionscount": 202
    },
    "positions": [
        {
            "azimuth": 22.51,
            "dec": 25.41265476,
            "eclipsed": false,
            "elevation": -20.98,
            "ra": 297.78221302,
            "sataltitude": 654.61,
            "satlatitude": 72.18845763,
            "satlongitude": 167.33046475,
            "timestamp": 1606435311
        }
    ]
}
{
    "info": {
        "satid": 36795,
        "satname": "CARTOSAT 2B",
        "transactionscount": 203
    },
    "positions": [
        {
            "azimuth": 22.58,
            "dec": 25.39641268,
            "eclipsed": false,
            "elevation": -20.98,
            "ra": 297.70943905,
            "sataltitude": 654.6,
            "satlatitude": 72.13366897,
            "satlongitude": 167.23710445,
            "timestamp": 1606435312
        }
    ]
}

{
    "info": {
        "satid": 36415,
        "satname": "YAOGAN 9C",
        "transactionscount": 204
    },
    "positions": [
        {
            "azimuth": 27.76,
            "dec": 18.02111449,
            "eclipsed": false,
            "elevation": -27.07,
            "ra": 295.0982708,
            "sataltitude": 996.6,
            "satlatitude": 61.2929786,
            "satlongitude": -168.37376883,
            "timestamp": 1606435313
        }
    ]
}
{
    "info": {
        "satid": 36414,
        "satname": "YAOGAN 9B",
        "transactionscount": 205
    },
    "positions": [
        {
            "azimuth": 31,
            "dec": 17.71627609,
            "eclipsed": false,
            "elevation": -26.16,
            "ra": 291.92736618,
            "sataltitude": 985.02,
            "satlatitude": 60.04129346,
            "satlongitude": -174.71464659,
            "timestamp": 1606435314
        }
    ]
}
{
    "info": {
        "satid": 36413,
        "satname": "YAOGAN 9A",
        "transactionscount": 206
    },
    "positions": [
        {
            "azimuth": 52.75,
            "dec": 10.54229143,
            "eclipsed": false,
            "elevation": -22.36,
            "ra": 272.46271341,
            "sataltitude": 903.33,
            "satlatitude": 47.1301816,
            "satlongitude": 158.37175562,
            "timestamp": 1606435314
        }
    ]
}
{
    "info": {
        "satid": 36121,
        "satname": "YAOGAN 8",
        "transactionscount": 207
    },
    "positions": [
        {
            "azimuth": 222.79,
            "dec": -51.80673725,
            "eclipsed": true,
            "elevation": -25.78,
            "ra": 59.72652945,
            "sataltitude": 1232.99,
            "satlatitude": -15.3678938,
            "satlongitude": 34.17538953,
            "timestamp": 1606435315
        }
    ]
}
{
    "info": {
        "satid": 36110,
        "satname": "YAOGAN 7",
        "transactionscount": 208
    },
    "positions": [
        {
            "azimuth": 145.96,
            "dec": -60.00263169,
            "eclipsed": false,
            "elevation": -28.96,
            "ra": 219.81444352,
            "sataltitude": 646.61,
            "satlatitude": -18.9615107,
            "satlongitude": 107.10917297,
            "timestamp": 1606435316
        }
    ]
}
{
    "info": {
        "satid": 35931,
        "satname": "OCEANSAT 2",
        "transactionscount": 209
    },
    "positions": [
        {
            "azimuth": 275.28,
            "dec": -16.13907797,
            "eclipsed": true,
            "elevation": -31.42,
            "ra": 23.1466502,
            "sataltitude": 724.98,
            "satlatitude": 15.68694752,
            "satlongitude": -4.29052967,
            "timestamp": 1606435316
        }
    ]
}
{
    "info": {
        "satid": 35870,
        "satname": "SUMBANDILA",
        "transactionscount": 210
    },
    "positions": [
        {
            "azimuth": 248.63,
            "dec": -44.33439058,
            "eclipsed": false,
            "elevation": -72.99,
            "ra": 343.29450509,
            "sataltitude": 375.15,
            "satlatitude": -44.08849555,
            "satlongitude": -60.78740048,
            "timestamp": 1606435318
        }
    ]
}
{
    "info": {
        "satid": 34839,
        "satname": "YAOGAN 6",
        "transactionscount": 211
    },
    "positions": [
        {
            "azimuth": 83.8,
            "dec": 12.99955407,
            "eclipsed": false,
            "elevation": 12.47,
            "ra": 225.49392354,
            "sataltitude": 471.91,
            "satlatitude": 40.28504331,
            "satlongitude": 90.2980998,
            "timestamp": 1606435319
        }
    ]
}
{
    "info": {
        "satid": 33331,
        "satname": "GEOEYE 1",
        "transactionscount": 212
    },
    "positions": [
        {
            "azimuth": 131.77,
            "dec": -55.14971481,
            "eclipsed": false,
            "elevation": -51.29,
            "ra": 266.02252286,
            "sataltitude": 691.6,
            "satlatitude": -42.6824451,
            "satlongitude": 149.48924707,
            "timestamp": 1606435319
        }
    ]
}
{
    "info": {
        "satid": 33105,
        "satname": "JASON 2",
        "transactionscount": 213
    },
    "positions": [
        {
            "azimuth": 145.22,
            "dec": -60.40482274,
            "eclipsed": false,
            "elevation": -60.63,
            "ra": 286.29887229,
            "sataltitude": 1328.11,
            "satlatitude": -62.86563365,
            "satlongitude": 168.2053043,
            "timestamp": 1606435320
        }
    ]
}
{
    "info": {
        "satid": 32783,
        "satname": "CARTOSAT 2A",
        "transactionscount": 214
    },
    "positions": [
        {
            "azimuth": 219.68,
            "dec": -57.57539912,
            "eclipsed": false,
            "elevation": -62.53,
            "ra": 354.12975468,
            "sataltitude": 658.43,
            "satlatitude": -59.52380257,
            "satlongitude": -24.04824086,
            "timestamp": 1606435321
        }
    ]
}
{
    "info": {
        "satid": 32476,
        "satname": "TECSAR",
        "transactionscount": 215
    },
    "positions": [
        {
            "azimuth": 280.55,
            "dec": -29.44136693,
            "eclipsed": true,
            "elevation": -60.38,
            "ra": 354.86446165,
            "sataltitude": 520.39,
            "satlatitude": -13.84983082,
            "satlongitude": -47.71243802,
            "timestamp": 1606435322
        }
    ]
}
{
    "info": {
        "satid": 32382,
        "satname": "RADARSAT 2",
        "transactionscount": 216
    },
    "positions": [
        {
            "azimuth": 330.4,
            "dec": -24.00432144,
            "eclipsed": false,
            "elevation": -71.88,
            "ra": 330.6809182,
            "sataltitude": 796.53,
            "satlatitude": -9.37108379,
            "satlongitude": -89.26359043,
            "timestamp": 1606435325
        }
    ]
}
{
    "info": {
        "satid": 29710,
        "satname": "CARTOSAT 2AT",
        "transactionscount": 217
    },
    "positions": [
        {
            "azimuth": 332.82,
            "dec": 16.37669128,
            "eclipsed": true,
            "elevation": -28.94,
            "ra": 345.73299245,
            "sataltitude": 631.71,
            "satlatitude": 62.0420176,
            "satlongitude": -42.72443136,
            "timestamp": 1606435326
        }
    ]
}
{
    "info": {
        "satid": 29709,
        "satname": "LAPAN-TUBSAT",
        "transactionscount": 218
    },
    "positions": [
        {
            "azimuth": 26.49,
            "dec": 6.45072593,
            "eclipsed": false,
            "elevation": -39.82,
            "ra": 300.87366759,
            "sataltitude": 630.98,
            "satlatitude": 47.21824059,
            "satlongitude": -146.47359072,
            "timestamp": 1606435327
        }
    ]
}
{
    "info": {
        "satid": 29268,
        "satname": "KOMPSAT 2",
        "transactionscount": 219
    },
    "positions": [
        {
            "azimuth": 298.54,
            "dec": -6.99039179,
            "eclipsed": true,
            "elevation": -38.97,
            "ra": 4.5132427,
            "sataltitude": 699.32,
            "satlatitude": 25.14744087,
            "satlongitude": -30.4739526,
            "timestamp": 1606435328
        }
    ]
}
{
    "info": {
        "satid": 29228,
        "satname": "RESURS DK-1",
        "transactionscount": 220
    },
    "positions": [
        {
            "azimuth": 24.07,
            "dec": 19.94632462,
            "eclipsed": false,
            "elevation": -26.29,
            "ra": 298.16227517,
            "sataltitude": 573.32,
            "satlatitude": 67.49174392,
            "satlongitude": -173.97162762,
            "timestamp": 1606435329
        }
    ]
}
{
    "info": {
        "satid": 29079,
        "satname": "EROS B",
        "transactionscount": 221
    },
    "positions": [
        {
            "azimuth": 246.54,
            "dec": -33.88652609,
            "eclipsed": true,
            "elevation": -25.95,
            "ra": 43.89149844,
            "sataltitude": 503.18,
            "satlatitude": 3.54795911,
            "satlongitude": 22.10424287,
            "timestamp": 1606435329
        }
    ]
}

{
    "info": {
        "satid": 28931,
        "satname": "ALOS",
        "transactionscount": 222
    },
    "positions": [
        {
            "azimuth": 189.1,
            "dec": -60.48831266,
            "eclipsed": false,
            "elevation": -69.3,
            "ra": 327.4526381,
            "sataltitude": 712.21,
            "satlatitude": -77.8037846,
            "satlongitude": -77.53530946,
            "timestamp": 1606435330
        }
    ]
}
{
    "info": {
        "satid": 28893,
        "satname": "SINAH 1",
        "transactionscount": 223
    },
    "positions": [
        {
            "azimuth": 229.1,
            "dec": -47.29590846,
            "eclipsed": true,
            "elevation": -26.14,
            "ra": 54.62161108,
            "sataltitude": 703,
            "satlatitude": -8.36321055,
            "satlongitude": 32.01201577,
            "timestamp": 1606435331
        }
    ]
}
{
    "info": {
        "satid": 28891,
        "satname": "TOPSAT",
        "transactionscount": 224
    },
    "positions": [
        {
            "azimuth": 165.4,
            "dec": -65.2891684,
            "eclipsed": false,
            "elevation": -63.24,
            "ra": 305.08924799,
            "sataltitude": 720.03,
            "satlatitude": -78.84181885,
            "satlongitude": 164.5490225,
            "timestamp": 1606435332
        }
    ]
}
{
    "info": {
        "satid": 28649,
        "satname": "CARTOSAT-1",
        "transactionscount": 225
    },
    "positions": [
        {
            "azimuth": 95.57,
            "dec": -25.49972366,
            "eclipsed": false,
            "elevation": -35.2,
            "ra": 256.64726871,
            "sataltitude": 620.2,
            "satlatitude": 3.95712406,
            "satlongitude": 150.8874787,
            "timestamp": 1606435333
        }
    ]
}
{
    "info": {
        "satid": 28220,
        "satname": "TANSUO 1",
        "transactionscount": 226
    },
    "positions": [
        {
            "azimuth": 0.72,
            "dec": 45.81673932,
            "eclipsed": true,
            "elevation": -3.98,
            "ra": 320.05009629,
            "sataltitude": 567.3,
            "satlatitude": 67.66072806,
            "satlongitude": 75.27628779,
            "timestamp": 1606435333
        }
    ]
}
{
    "info": {
        "satid": 28376,
        "satname": "AURA",
        "transactionscount": 227
    },
    "positions": [
        {
            "azimuth": 118.98,
            "dec": -46.0545263,
            "eclipsed": false,
            "elevation": -74.61,
            "ra": 301.4788503,
            "sataltitude": 721.83,
            "satlatitude": -48.28343454,
            "satlongitude": -145.28276728,
            "timestamp": 1606435334
        }
    ]
}
{
    "info": {
        "satid": 28254,
        "satname": "ROCSAT 2",
        "transactionscount": 228
    },
    "positions": [
        {
            "azimuth": 176.31,
            "dec": -76.86977442,
            "eclipsed": false,
            "elevation": -53.05,
            "ra": 310.85449406,
            "sataltitude": 917.35,
            "satlatitude": -70.92678353,
            "satlongitude": 84.89018194,
            "timestamp": 1606435334
        }
    ]
}
{
    "info": {
        "satid": 28220,
        "satname": "TANSUO 1",
        "transactionscount": 229
    },
    "positions": [
        {
            "azimuth": 0.62,
            "dec": 45.91972176,
            "eclipsed": true,
            "elevation": -3.88,
            "ra": 320.19619062,
            "sataltitude": 567.3,
            "satlatitude": 67.54397938,
            "satlongitude": 75.15079397,
            "timestamp": 1606435335
        }
    ]
}
{
    "info": {
        "satid": 28057,
        "satname": "CBERS 2",
        "transactionscount": 230
    },
    "positions": [
        {
            "azimuth": 325.98,
            "dec": 37.51333118,
            "eclipsed": true,
            "elevation": -2.15,
            "ra": 5.79893714,
            "sataltitude": 782.53,
            "satlatitude": 60.65968896,
            "satlongitude": 40.56132516,
            "timestamp": 1606435336
        }
    ]
}
{
    "info": {
        "satid": 28051,
        "satname": "IRS P6",
        "transactionscount": 231
    },
    "positions": [
        {
            "azimuth": 16.7,
            "dec": 25.19877101,
            "eclipsed": false,
            "elevation": -22.79,
            "ra": 304.15990885,
            "sataltitude": 828.89,
            "satlatitude": 74.29352289,
            "satlongitude": -169.6661481,
            "timestamp": 1606435336
        }
    ]
}
{
    "info": {
        "satid": 27840,
        "satname": "MONITOR-E/SL-19",
        "transactionscount": 232
    },
    "positions": [
        {
            "azimuth": 24.49,
            "dec": -3.72638091,
            "eclipsed": false,
            "elevation": -51.08,
            "ra": 305.95127867,
            "sataltitude": 774.33,
            "satlatitude": 28.49085907,
            "satlongitude": -132.42151197,
            "timestamp": 1606435337
        }
    ]
}
{
    "info": {
        "satid": 27597,
        "satname": "ADEOS 2",
        "transactionscount": 233
    },
    "positions": [
        {
            "azimuth": 169.82,
            "dec": -57.32139513,
            "eclipsed": false,
            "elevation": -72.46,
            "ra": 315.35170093,
            "sataltitude": 827.13,
            "satlatitude": -72.10472533,
            "satlongitude": -123.75561741,
            "timestamp": 1606435338
        }
    ]
}
{
    "info": {
        "satid": 27559,
        "satname": "ALSAT 1",
        "transactionscount": 234
    },
    "positions": [
        {
            "azimuth": 240.9,
            "dec": -28.14433563,
            "eclipsed": true,
            "elevation": -9.13,
            "ra": 63.457093,
            "sataltitude": 656.96,
            "satlatitude": 17.7803228,
            "satlongitude": 42.14772108,
            "timestamp": 1606435339
        }
    ]
}
{
    "info": {
        "satid": 27430,
        "satname": "HAIYANG 1",
        "transactionscount": 235
    },
    "positions": [
        {
            "azimuth": 348.4,
            "dec": 45.54551347,
            "eclipsed": true,
            "elevation": -2.98,
            "ra": 337.70417489,
            "sataltitude": 805.81,
            "satlatitude": 69.25327345,
            "satlongitude": 57.69732122,
            "timestamp": 1606435340
        }
    ]
}
{
    "info": {
        "satid": 27424,
        "satname": "AQUA",
        "transactionscount": 236
    },
    "positions": [
        {
            "azimuth": 77.29,
            "dec": -31.13401229,
            "eclipsed": false,
            "elevation": -65.51,
            "ra": 292.88273728,
            "sataltitude": 710.69,
            "satlatitude": -19.06077491,
            "satlongitude": -153.89029067,
            "timestamp": 1606435341
        }
    ]
}
{
    "info": {
        "satid": 27421,
        "satname": "SPOT 5",
        "transactionscount": 237
    },
    "positions": [
        {
            "azimuth": 103.52,
            "dec": -33.03390503,
            "eclipsed": false,
            "elevation": -39.31,
            "ra": 257.1275454,
            "sataltitude": 772.95,
            "satlatitude": -7.65282625,
            "satlongitude": 152.23040718,
            "timestamp": 1606435342
        }
    ]
}
{
    "info": {
        "satid": 27386,
        "satname": "ENVISAT",
        "transactionscount": 238
    },
    "positions": [
        {
            "azimuth": 182.32,
            "dec": -83.41072525,
            "eclipsed": false,
            "elevation": -46.57,
            "ra": 334.41117357,
            "sataltitude": 788.6,
            "satlatitude": -58.69019113,
            "satlongitude": 70.02801628,
            "timestamp": 1606435344
        }
    ]
}
{
    "info": {
        "satid": 27004,
        "satname": "MAROC TUBSAT",
        "transactionscount": 239
    },
    "positions": [
        {
            "azimuth": 305.32,
            "dec": 22.47398997,
            "eclipsed": true,
            "elevation": -4.99,
            "ra": 22.89821249,
            "sataltitude": 1008.32,
            "satlatitude": 51.37008698,
            "satlongitude": 24.87252009,
            "timestamp": 1606435344
        }
    ]
}

{
    "info": {
        "satid": 27003,
        "satname": "BADR B",
        "transactionscount": 240
    },
    "positions": [
        {
            "azimuth": 171.12,
            "dec": -69.66088721,
            "eclipsed": false,
            "elevation": -59.66,
            "ra": 307.89582828,
            "sataltitude": 1016.22,
            "satlatitude": -80.50916092,
            "satlongitude": 124.95282963,
            "timestamp": 1606435345
        }
    ]
}
{
    "info": {
        "satid": 27001,
        "satname": "METEOR 3M",
        "transactionscount": 241
    },
    "positions": [
        {
            "azimuth": 284.35,
            "dec": 10.19358823,
            "eclipsed": true,
            "elevation": -0.87,
            "ra": 41.15620587,
            "sataltitude": 1002.43,
            "satlatitude": 40.47828935,
            "satlongitude": 33.30253499,
            "timestamp": 1606435346
        }
    ]
}
{
    "info": {
        "satid": 26997,
        "satname": "JASON",
        "transactionscount": 242
    },
    "positions": [
        {
            "azimuth": 322.28,
            "dec": -4.22870205,
            "eclipsed": true,
            "elevation": -47.88,
            "ra": 345.40234351,
            "sataltitude": 1331.42,
            "satlatitude": 25.37892187,
            "satlongitude": -64.52787887,
            "timestamp": 1606435347
        }
    ]
}
{
    "info": {
        "satid": 26957,
        "satname": "TES",
        "transactionscount": 243
    },
    "positions": [
        {
            "azimuth": 25.26,
            "dec": 5.82790567,
            "eclipsed": false,
            "elevation": -40.89,
            "ra": 302.23210641,
            "sataltitude": 541.75,
            "satlatitude": 46.73884439,
            "satlongitude": -144.01884832,
            "timestamp": 1606435348
        }
    ]
}
{
    "info": {
        "satid": 26620,
        "satname": "SAC C",
        "transactionscount": 244
    },
    "positions": [
        {
            "azimuth": 349.58,
            "dec": 43.27465106,
            "eclipsed": true,
            "elevation": -5.55,
            "ra": 335.3857308,
            "sataltitude": 708.13,
            "satlatitude": 70.78075601,
            "satlongitude": 57.57000424,
            "timestamp": 1606435348
        }
    ]
}
{
    "info": {
        "satid": 26619,
        "satname": "EO 1",
        "transactionscount": 245
    },
    "positions": [
        {
            "azimuth": 12.75,
            "dec": -24.81218278,
            "eclipsed": false,
            "elevation": -74.31,
            "ra": 317.33603256,
            "sataltitude": 682.98,
            "satlatitude": -11.03794874,
            "satlongitude": -112.01326681,
            "timestamp": 1606435349
        }
    ]
}
{
    "info": {
        "satid": 26548,
        "satname": "TIUNGSAT 1",
        "transactionscount": 246
    },
    "positions": [
        {
            "azimuth": 133.78,
            "dec": -53.60055434,
            "eclipsed": false,
            "elevation": -65.69,
            "ra": 290.90147021,
            "sataltitude": 597.06,
            "satlatitude": -56.08088391,
            "satlongitude": -174.4738208,
            "timestamp": 1606435350
        }
    ]
}
{
    "info": {
        "satid": 26032,
        "satname": "KOMPSAT",
        "transactionscount": 247
    },
    "positions": [
        {
            "azimuth": 182.09,
            "dec": -73.89399698,
            "eclipsed": false,
            "elevation": -56.18,
            "ra": 324.98577101,
            "sataltitude": 689,
            "satlatitude": -75.73238522,
            "satlongitude": 66.83288943,
            "timestamp": 1606435351
        }
    ]
}
{
    "info": {
        "satid": 25994,
        "satname": "TERRA",
        "transactionscount": 248
    },
    "positions": [
        {
            "azimuth": 354.42,
            "dec": 25.49888287,
            "eclipsed": false,
            "elevation": -24.12,
            "ra": 326.8935648,
            "sataltitude": 715.02,
            "satlatitude": 79.95622534,
            "satlongitude": -77.12043091,
            "timestamp": 1606435352
        }
    ]
}
{
    "info": {
        "satid": 25940,
        "satname": "CBERS 1",
        "transactionscount": 249
    },
    "positions": [
        {
            "azimuth": 61.05,
            "dec": -23.55314514,
            "eclipsed": false,
            "elevation": -62.36,
            "ra": 294.84190329,
            "sataltitude": 779.46,
            "satlatitude": -6.16699597,
            "satlongitude": -149.56012853,
            "timestamp": 1606435353
        }
    ]
}
{
    "info": {
        "satid": 25919,
        "satname": "IKONOS 2",
        "transactionscount": 250
    },
    "positions": [
        {
            "azimuth": 31.42,
            "dec": -9.25722481,
            "eclipsed": false,
            "elevation": -55.49,
            "ra": 303.73346287,
            "sataltitude": 612.62,
            "satlatitude": 19.13973302,
            "satlongitude": -135.7915797,
            "timestamp": 1606435353
        }
    ]
}
{
    "info": {
        "satid": 25860,
        "satname": "OKEAN O",
        "transactionscount": 251
    },
    "positions": [
        {
            "azimuth": 320.56,
            "dec": -16.39325244,
            "eclipsed": false,
            "elevation": -61.25,
            "ra": 339.70609323,
            "sataltitude": 641.95,
            "satlatitude": 6.16093594,
            "satlongitude": -74.15440295,
            "timestamp": 1606435354
        }
    ]
}
{
    "info": {
        "satid": 25789,
        "satname": "QUIKSCAT",
        "transactionscount": 252
    },
    "positions": [
        {
            "azimuth": 128.44,
            "dec": -44.2286701,
            "eclipsed": false,
            "elevation": -24.22,
            "ra": 227.01709578,
            "sataltitude": 660.79,
            "satlatitude": -4.11399896,
            "satlongitude": 116.34577921,
            "timestamp": 1606435355
        }
    ]
}
{
    "info": {
        "satid": 25758,
        "satname": "IRS P4 (OCEANSAT 1)",
        "transactionscount": 253
    },
    "positions": [
        {
            "azimuth": 134.49,
            "dec": -55.30529405,
            "eclipsed": false,
            "elevation": -39.43,
            "ra": 245.02794675,
            "sataltitude": 730.04,
            "satlatitude": -29.18017864,
            "satlongitude": 128.66354765,
            "timestamp": 1606435356
        }
    ]
}
{
    "info": {
        "satid": 25757,
        "satname": "TUBSAT",
        "transactionscount": 254
    },
    "positions": [
        {
            "azimuth": 35.12,
            "dec": 15.15928958,
            "eclipsed": false,
            "elevation": -27.19,
            "ra": 289.1512452,
            "sataltitude": 719.82,
            "satlatitude": 57.63262987,
            "satlongitude": 179.46565972,
            "timestamp": 1606435359
        }
    ]
}
{
    "info": {
        "satid": 25756,
        "satname": "KITSAT 3",
        "transactionscount": 255
    },
    "positions": [
        {
            "azimuth": 88.04,
            "dec": -37.46993897,
            "eclipsed": false,
            "elevation": -72.82,
            "ra": 299.31749275,
            "sataltitude": 716.24,
            "satlatitude": -32.19977092,
            "satlongitude": -144.98939424,
            "timestamp": 1606435362
        }
    ]
}
{
    "info": {
        "satid": 25693,
        "satname": "OSCAR 36 (UOSAT 12)",
        "transactionscount": 256
    },
    "positions": [
        {
            "azimuth": 141.2,
            "dec": -60.29518538,
            "eclipsed": false,
            "elevation": -39.03,
            "ra": 241.76214458,
            "sataltitude": 614.96,
            "satlatitude": -31.80878706,
            "satlongitude": 121.29578453,
            "timestamp": 1606435364
        }
    ]
}
{
    "info": {
        "satid": 25682,
        "satname": "LANDSAT 7",
        "transactionscount": 257
    },
    "positions": [
        {
            "azimuth": 206.6,
            "dec": -62.94241673,
            "eclipsed": false,
            "elevation": -62.02,
            "ra": 348.46519588,
            "sataltitude": 729.29,
            "satlatitude": -69.21919761,
            "satlongitude": -15.55255775,
            "timestamp": 1606435365
        }
    ]
}

{
    "info": {
        "satid": 25636,
        "satname": "SUNSAT",
        "transactionscount": 258
    },
    "positions": [
        {
            "azimuth": 222.57,
            "dec": -39.80424297,
            "eclipsed": true,
            "elevation": -7.28,
            "ra": 80.37191478,
            "sataltitude": 796.69,
            "satlatitude": 11.31973574,
            "satlongitude": 50.87108005,
            "timestamp": 1606435366
        }
    ]
}
{
    "info": {
        "satid": 25616,
        "satname": "ROCSAT 1",
        "transactionscount": 259
    },
    "positions": [
        {
            "azimuth": 262.15,
            "dec": -38.03836414,
            "eclipsed": true,
            "elevation": -61.26,
            "ra": 358.3056589,
            "sataltitude": 490.44,
            "satlatitude": -27.20185136,
            "satlongitude": -39.57058431,
            "timestamp": 1606435366
        }
    ]
}
{
    "info": {
        "satid": 25504,
        "satname": "SCD 2",
        "transactionscount": 260
    },
    "positions": [
        {
            "azimuth": 62.79,
            "dec": -28.37358316,
            "eclipsed": false,
            "elevation": -68.86,
            "ra": 299.75900842,
            "sataltitude": 734.26,
            "satlatitude": -15.8149436,
            "satlongitude": -142.03121695,
            "timestamp": 1606435367
        }
    ]
}
{
    "info": {
        "satid": 25397,
        "satname": "TECHSAT 1B",
        "transactionscount": 261
    },
    "positions": [
        {
            "azimuth": 61.54,
            "dec": -21.12933997,
            "eclipsed": false,
            "elevation": -58.59,
            "ra": 291.77377561,
            "sataltitude": 815.33,
            "satlatitude": -1.32923882,
            "satlongitude": -154.48987137,
            "timestamp": 1606435368
        }
    ]
}
{
    "info": {
        "satid": 25396,
        "satname": "TMSAT",
        "transactionscount": 262
    },
    "positions": [
        {
            "azimuth": 38.48,
            "dec": 4.91240614,
            "eclipsed": false,
            "elevation": -37.27,
            "ra": 291.41081587,
            "sataltitude": 816.99,
            "satlatitude": 42.77283538,
            "satlongitude": -162.75497388,
            "timestamp": 1606435369
        }
    ]
}
{
    "info": {
        "satid": 25395,
        "satname": "FASAT B",
        "transactionscount": 263
    },
    "positions": [
        {
            "azimuth": 62.62,
            "dec": -22.12222693,
            "eclipsed": false,
            "elevation": -59.45,
            "ra": 292.04169896,
            "sataltitude": 812.28,
            "satlatitude": -3.12027827,
            "satlongitude": -154.09717512,
            "timestamp": 1606435370
        }
    ]
}
{
    "info": {
        "satid": 25394,
        "satname": "RESURS O1-N4",
        "transactionscount": 264
    },
    "positions": [
        {
            "azimuth": 216.15,
            "dec": -62.79661848,
            "eclipsed": false,
            "elevation": -51.33,
            "ra": 14.83602146,
            "sataltitude": 830.26,
            "satlatitude": -51.85004834,
            "satlongitude": 9.62798134,
            "timestamp": 1606435371
        }
    ]
}
{
    "info": {
        "satid": 25260,
        "satname": "SPOT 4",
        "transactionscount": 265
    },
    "positions": [
        {
            "azimuth": 181.94,
            "dec": -71.06013972,
            "eclipsed": false,
            "elevation": -59.05,
            "ra": 323.97518293,
            "sataltitude": 742.6,
            "satlatitude": -81.26455268,
            "satlongitude": 63.5462445,
            "timestamp": 1606435371
        }
    ]
}
{
    "info": {
        "satid": 24971,
        "satname": "IRS 1D",
        "transactionscount": 266
    },
    "positions": [
        {
            "azimuth": 45.15,
            "dec": -6.35358516,
            "eclipsed": false,
            "elevation": -47.46,
            "ra": 292.39181187,
            "sataltitude": 764.78,
            "satlatitude": 24.49832569,
            "satlongitude": -155.67415049,
            "timestamp": 1606435373
        }
    ]
}
{
    "info": {
        "satid": 24883,
        "satname": "ORBVIEW 2 (SEASTAR)",
        "transactionscount": 267
    },
    "positions": [
        {
            "azimuth": 137.45,
            "dec": -55.28912943,
            "eclipsed": false,
            "elevation": -64.91,
            "ra": 290.82959825,
            "sataltitude": 803.51,
            "satlatitude": -58.55811182,
            "satlongitude": -176.77920433,
            "timestamp": 1606435373
        }
    ]
}
{
    "info": {
        "satid": 24277,
        "satname": "ADEOS",
        "transactionscount": 268
    },
    "positions": [
        {
            "azimuth": 14.36,
            "dec": 0.80865587,
            "eclipsed": false,
            "elevation": -48.11,
            "ra": 311.70777481,
            "sataltitude": 798.66,
            "satlatitude": 36.53926538,
            "satlongitude": -123.19182304,
            "timestamp": 1606435374
        }
    ]
}
{
    "info": {
        "satid": 23940,
        "satname": "TOMS EP",
        "transactionscount": 269
    },
    "positions": [
        {
            "azimuth": 259.15,
            "dec": -18.70672614,
            "eclipsed": true,
            "elevation": -16.24,
            "ra": 45.38309559,
            "sataltitude": 693.6,
            "satlatitude": 19.8653861,
            "satlongitude": 25.44861582,
            "timestamp": 1606435375
        }
    ]
}
{
    "info": {
        "satid": 23827,
        "satname": "IRS B3",
        "transactionscount": 270
    },
    "positions": [
        {
            "azimuth": 77.21,
            "dec": -34.66929811,
            "eclipsed": false,
            "elevation": -73.26,
            "ra": 301.24442226,
            "sataltitude": 824.95,
            "satlatitude": -27.69936004,
            "satlongitude": -140.68302201,
            "timestamp": 1606435376
        }
    ]
}
{
    "info": {
        "satid": 23751,
        "satname": "IRS 1C",
        "transactionscount": 271
    },
    "positions": [
        {
            "azimuth": 339.69,
            "dec": 46.68208259,
            "eclipsed": true,
            "elevation": 0.99,
            "ra": 351.55216915,
            "sataltitude": 826.69,
            "satlatitude": 63.8691285,
            "satlongitude": 53.68863554,
            "timestamp": 1606435376
        }
    ]
}
{
    "info": {
        "satid": 23710,
        "satname": "RADARSAT",
        "transactionscount": 272
    },
    "positions": [
        {
            "azimuth": 358.49,
            "dec": 13.00403852,
            "eclipsed": false,
            "elevation": -36.8,
            "ra": 322.51797158,
            "sataltitude": 798.37,
            "satlatitude": 58.53627016,
            "satlongitude": -102.7441805,
            "timestamp": 1606435377
        }
    ]
}
{
    "info": {
        "satid": 23657,
        "satname": "SICH 1",
        "transactionscount": 273
    },
    "positions": [
        {
            "azimuth": 352.33,
            "dec": 2.39652375,
            "eclipsed": false,
            "elevation": -47.21,
            "ra": 326.45337943,
            "sataltitude": 616.27,
            "satlatitude": 40.4961782,
            "satlongitude": -95.60792757,
            "timestamp": 1606435378
        }
    ]
}
{
    "info": {
        "satid": 23560,
        "satname": "ERS 2",
        "transactionscount": 274
    },
    "positions": [
        {
            "azimuth": 169.66,
            "dec": -74.03508631,
            "eclipsed": false,
            "elevation": -26.7,
            "ra": 177.20931216,
            "sataltitude": 501.08,
            "satlatitude": -20.11947204,
            "satlongitude": 83.96024602,
            "timestamp": 1606435379
        }
    ]
}
{
    "info": {
        "satid": 23342,
        "satname": "RESURS O1",
        "transactionscount": 275
    },
    "positions": [
        {
            "azimuth": 177.9,
            "dec": -71.90961133,
            "eclipsed": false,
            "elevation": -58.2,
            "ra": 317.37141575,
            "sataltitude": 659.86,
            "satlatitude": -79.32820648,
            "satlongitude": 84.23801725,
            "timestamp": 1606435380
        }
    ]
}

{
    "info": {
        "satid": 23323,
        "satname": "IRS P2",
        "transactionscount": 276
    },
    "positions": [
        {
            "azimuth": 195.33,
            "dec": -76.98605257,
            "eclipsed": false,
            "elevation": -47.15,
            "ra": 13.82097575,
            "sataltitude": 835.24,
            "satlatitude": -57.17281922,
            "satlongitude": 45.913806,
            "timestamp": 1606435380
        }
    ]
}
{
    "info": {
        "satid": 23317,
        "satname": "OKEAN 4",
        "transactionscount": 277
    },
    "positions": [
        {
            "azimuth": 173,
            "dec": -63.10145362,
            "eclipsed": false,
            "elevation": -66.77,
            "ra": 314.96198961,
            "sataltitude": 628.12,
            "satlatitude": -82.56619847,
            "satlongitude": -146.36481893,
            "timestamp": 1606435381
        }
    ]
}
{
    "info": {
        "satid": 22823,
        "satname": "SPOT 3",
        "transactionscount": 278
    },
    "positions": [
        {
            "azimuth": 36.34,
            "dec": 41.73407408,
            "eclipsed": false,
            "elevation": 4.53,
            "ra": 269.21321799,
            "sataltitude": 847.34,
            "satlatitude": 56.9298762,
            "satlongitude": 100.36876491,
            "timestamp": 1606435384
        }
    ]
}
{
    "info": {
        "satid": 22076,
        "satname": "TOPEX/POSEIDON",
        "transactionscount": 279
    },
    "positions": [
        {
            "azimuth": 222.4,
            "dec": -48.62848587,
            "eclipsed": false,
            "elevation": -77.72,
            "ra": 333.68950601,
            "sataltitude": 1352.44,
            "satlatitude": -54.42473494,
            "satlongitude": -79.51739399,
            "timestamp": 1606435386
        }
    ]
}
{
    "info": {
        "satid": 21688,
        "satname": "IRS 1B",
        "transactionscount": 280
    },
    "positions": [
        {
            "azimuth": 30.25,
            "dec": 12.18926576,
            "eclipsed": false,
            "elevation": -32.45,
            "ra": 295.51438711,
            "sataltitude": 906.15,
            "satlatitude": 53.8182951,
            "satlongitude": -160.95757649,
            "timestamp": 1606435386
        }
    ]
}
{
    "info": {
        "satid": 21574,
        "satname": "ERS 1",
        "transactionscount": 281
    },
    "positions": [
        {
            "azimuth": 13.14,
            "dec": 30.59056133,
            "eclipsed": false,
            "elevation": -17.96,
            "ra": 306.75359989,
            "sataltitude": 773.85,
            "satlatitude": 79.97980683,
            "satlongitude": 159.84589451,
            "timestamp": 1606435387
        }
    ]
}
{
    "info": {
        "satid": 21397,
        "satname": "OKEAN 3",
        "transactionscount": 282
    },
    "positions": [
        {
            "azimuth": 55.66,
            "dec": 17.83987989,
            "eclipsed": false,
            "elevation": -10.69,
            "ra": 262.97445211,
            "sataltitude": 605.79,
            "satlatitude": 50.73591888,
            "satlongitude": 125.83998353,
            "timestamp": 1606435388
        }
    ]
}
{
    "info": {
        "satid": 20510,
        "satname": "OKEAN 2",
        "transactionscount": 283
    },
    "positions": [
        {
            "azimuth": 214.33,
            "dec": -57.08702913,
            "eclipsed": false,
            "elevation": -67.2,
            "ra": 344.83404495,
            "sataltitude": 597.39,
            "satlatitude": -64.64908678,
            "satlongitude": -41.08093315,
            "timestamp": 1606435389
        }
    ]
}
{
    "info": {
        "satid": 20478,
        "satname": "MOS 1B (MOMO 1B)",
        "transactionscount": 284
    },
    "positions": [
        {
            "azimuth": 318.49,
            "dec": -31.93968338,
            "eclipsed": false,
            "elevation": -79.39,
            "ra": 329.52156202,
            "sataltitude": 915.88,
            "satlatitude": -24.53126699,
            "satlongitude": -91.2717603,
            "timestamp": 1606435389
        }
    ]
}
{
    "info": {
        "satid": 20436,
        "satname": "SPOT 2",
        "transactionscount": 285
    },
    "positions": [
        {
            "azimuth": 138.58,
            "dec": -22.2635215,
            "eclipsed": false,
            "elevation": 15.34,
            "ra": 185.07709022,
            "sataltitude": 763.5,
            "satlatitude": 28.03927883,
            "satlongitude": 85.72630581,
            "timestamp": 1606435390
        }
    ]
}
{
    "info": {
        "satid": 19274,
        "satname": "OKEAN 1",
        "transactionscount": 286
    },
    "positions": [
        {
            "azimuth": 156.34,
            "dec": -67.35912808,
            "eclipsed": false,
            "elevation": -56.72,
            "ra": 286.12237475,
            "sataltitude": 573.7,
            "satlatitude": -66.19929913,
            "satlongitude": 136.54423699,
            "timestamp": 1606435391
        }
    ]
}
{
    "info": {
        "satid": 18960,
        "satname": "IRS 1A",
        "transactionscount": 287
    },
    "positions": [
        {
            "azimuth": 173.14,
            "dec": -71.9966063,
            "eclipsed": false,
            "elevation": -57.58,
            "ra": 309.00282548,
            "sataltitude": 939.14,
            "satlatitude": -78.13706445,
            "satlongitude": 104.50123438,
            "timestamp": 1606435392
        }
    ]
}
{
    "info": {
        "satid": 18214,
        "satname": "COSMOS 1869",
        "transactionscount": 288
    },
    "positions": [
        {
            "azimuth": 2.49,
            "dec": 10.96474699,
            "eclipsed": false,
            "elevation": -38.82,
            "ra": 319.33997197,
            "sataltitude": 571.16,
            "satlatitude": 56.74347729,
            "satlongitude": -110.10103596,
            "timestamp": 1606435393
        }
    ]
}
{
    "info": {
        "satid": 17527,
        "satname": "MOS 1A (MOMO 1)",
        "transactionscount": 289
    },
    "positions": [
        {
            "azimuth": 310.36,
            "dec": -9.96877956,
            "eclipsed": true,
            "elevation": -49.72,
            "ra": 351.32422051,
            "sataltitude": 882.7,
            "satlatitude": 18.00812016,
            "satlongitude": -54.87417654,
            "timestamp": 1606435394
        }
    ]
}
{
    "info": {
        "satid": 16881,
        "satname": "COSMOS 1766",
        "transactionscount": 290
    },
    "positions": [
        {
            "azimuth": 93.31,
            "dec": -28.44935447,
            "eclipsed": false,
            "elevation": -43.6,
            "ra": 265.9720164,
            "sataltitude": 536.78,
            "satlatitude": -3.81894545,
            "satlongitude": 163.50099284,
            "timestamp": 1606435395
        }
    ]
}
{
    "info": {
        "satid": 16613,
        "satname": "SPOT 1",
        "transactionscount": 291
    },
    "positions": [
        {
            "azimuth": 78.52,
            "dec": -33.73413976,
            "eclipsed": false,
            "elevation": -70.37,
            "ra": 297.9462516,
            "sataltitude": 720.15,
            "satlatitude": -25.170746,
            "satlongitude": -146.41998396,
            "timestamp": 1606435395
        }
    ]
}
{
    "info": {
        "satid": 15331,
        "satname": "COSMOS 1602",
        "transactionscount": 292
    },
    "positions": [
        {
            "azimuth": 210.68,
            "dec": -55.09666292,
            "eclipsed": false,
            "elevation": -71.47,
            "ra": 337.70242337,
            "sataltitude": 539.78,
            "satlatitude": -65.28974526,
            "satlongitude": -60.68536094,
            "timestamp": 1606435396
        }
    ]
}
{
    "info": {
        "satid": 14780,
        "satname": "LANDSAT 5",
        "transactionscount": 293
    },
    "positions": [
        {
            "azimuth": 341.47,
            "dec": 39.37454959,
            "eclipsed": true,
            "elevation": -7.5,
            "ra": 345.5095429,
            "sataltitude": 590.6,
            "satlatitude": 68.74862881,
            "satlongitude": 46.51133904,
            "timestamp": 1606435397
        }
    ]
}

{
    "info": {
        "satid": 13367,
        "satname": "LANDSAT 4",
        "transactionscount": 294
    },
    "positions": [
        {
            "azimuth": 281.94,
            "dec": -3.5776649,
            "eclipsed": true,
            "elevation": -19.17,
            "ra": 29.11621564,
            "sataltitude": 517.43,
            "satlatitude": 33.10319761,
            "satlongitude": 13.7302194,
            "timestamp": 1606435398
        }
    ]
}
{
    "info": {
        "satid": 10967,
        "satname": "SEASAT 1",
        "transactionscount": 295
    },
    "positions": [
        {
            "azimuth": 244.26,
            "dec": -44.58193487,
            "eclipsed": true,
            "elevation": -47.81,
            "ra": 19.28440453,
            "sataltitude": 755.54,
            "satlatitude": -26.85910264,
            "satlongitude": -7.11891834,
            "timestamp": 1606435399
        }
    ]
}
{
    "info": {
        "satid": 10702,
        "satname": "LANDSAT 3",
        "transactionscount": 296
    },
    "positions": [
        {
            "azimuth": 10.73,
            "dec": 16.7487801,
            "eclipsed": false,
            "elevation": -32.4,
            "ra": 311.91482471,
            "sataltitude": 916.01,
            "satlatitude": 63.47657261,
            "satlongitude": -129.29604027,
            "timestamp": 1606435399
        }
    ]
}
{
    "info": {
        "satid": 7615,
        "satname": "LANDSAT 2",
        "transactionscount": 297
    },
    "positions": [
        {
            "azimuth": 7.65,
            "dec": 14.04622423,
            "eclipsed": false,
            "elevation": -35.45,
            "ra": 314.95494941,
            "sataltitude": 913.66,
            "satlatitude": 59.22773753,
            "satlongitude": -120.4185468,
            "timestamp": 1606435400
        }
    ]
}
{
    "info": {
        "satid": 6126,
        "satname": "LANDSAT 1 (ERTS 1)",
        "transactionscount": 298
    },
    "positions": [
        {
            "azimuth": 24.46,
            "dec": 4.79857208,
            "eclipsed": false,
            "elevation": -42.11,
            "ra": 303.39895048,
            "sataltitude": 902.61,
            "satlatitude": 42.765736,
            "satlongitude": -139.91030254,
            "timestamp": 1606435401
        }
    ]
}